### ISSUE TITLE
[Twilio-WhatsApp] Add oauth to adapter

### ISSUE THREAD

**Issue by nestoralonsovina** [BotBuilderCommunity/botbuilder-community-js#143]
Hello,

First of all, thanks for the implementation of the adapter.

We found out that the OAuth is not implemented in it, is there any reason for this? Or simply no one has tried to implement it yet. 

If it's the second case, we might try to implement and if you want we'll create a pull request to make it available for everyone.

Nestor

**Comment by iMicknl** [comment]
Good suggestion, @nestoralonsovina! Currently I didn't integrate OAuth yet, since that is something that isn't supported at any custom adapter yet.

However, it crossed my mind already and I gave it a try, but I faced some issues with integrating a custom adapter with the Bot Service. Feel free to work on it and share it with the community, would be highly appreciated. 

We could use this issue to discuss progress and architectural choices. I will have a look if I can find the work I did a while ago..

**Comment by iMicknl** [comment]
I think it would be great to have OAuth integrated for all custom adapters. It could possibly be integrated in the [`CustomWebAdapter` that I am building](https://github.com/BotBuilderCommunity/botbuilder-community-js/pull/141). However if I look at multiple adapters, for Alexa we would possibly like to use [Account Linking](https://developer.amazon.com/en-US/docs/alexa/account-linking/understand-account-linking.html), instead of the Azure Bot Service OAuth provider. 

I am not sure if I understand you correctly. If you just implement `IUserTokenProvider`, who is handling the OAuth request? The `BotFrameworkAdapter` is using a [`TokenApiClient`](https://github.com/microsoft/botbuilder-js/blob/b0c18362e681b50e398cb30f3d0b7268cd3a734c/libraries/botbuilder/src/botFrameworkAdapter.ts#L636) connected to the Azure Bot Service.

**Comment by nestoralonsovina** [comment]
Implementing ```IUserTokenProvider``` will imply using the ```TokenApiClient``` yes. The interface is just the 4 basic functions that have to be implemented to handle the auth.

If you want to implement it in other adapters, once I get something working (if I'm able to) I will extrapolate everything related to auth into a ```AuthDefaultAdapter``` who will extend ```DefaultAdapter``` and then be extended by the custom adapters. 

Does that sound good to you?

**Comment by iMicknl** [comment]
@nestoralonsovina I am also open for suggestions about how to integrate with this PR https://github.com/BotBuilderCommunity/botbuilder-community-js/pull/141. Would be great to have an easy option to optional add support for OAuth, while using `CustomWebAdapter`.

**Comment by nestoralonsovina** [comment]
@iMicknl I've taken a look at the PR, it seems interesting and a good concept, for the moment I'm just trying to get something to work adapting the Twilio Adapter. 

It'll surely need quite a bit of cleaning afterwards and making sure it's usable by someone who doesn't need the OAuth (since we'll be using it all the time I've not really paid much attention to that).

As an update, I've been able to get a valid SignIn link, I've not been able to test the rest of the functions since the OAuth Prompt doesn't work with the adapter. 

I've thought of either creating a new OAuthPrompt that works only with messages and doesn't try to send Cards or simply trying to make some transformation of the cards into messages.

**Comment by szul** [comment]
Yes, the Twitter adapter uses Oath for some of it's methods (the Twitter Activity API is a mess in general), but we currently only implement Oath for the owning user, so it's single-leg as opposed to multi-leg, which would be necessary to subscribe to other Twitter feeds you don't know.

**Comment by iMicknl** [comment]
@nestoralonsovina sounds good! Do you have your code somewhere? In the end we could transform OAuthPrompts (and other cards) to static text messages in the adapter or in a middleware.

@szul isn't that different? You are using OAuth for the authentication with the Twitter API, not to authenticate the user to an other provider, like we are trying to achieve with this proposal.

**Comment by szul** [comment]
@iMicknl I was assuming you were trying to OAuth to Twilio and/or WhatsApp.

**Comment by nestoralonsovina** [comment]
@iMicknl transforming cards into static text messages would be the ideal scenario in this case, for the moment I've just created a modified oauth prompt, replacing the function that sends the card with:
```
        if (this.settings.text) {
            await context.sendActivity(this.settings.text);
        }
        await context.sendActivity(this.settings.title);
        await context.sendActivity(
            await (context.adapter as IUserTokenProvider).getSignInLink(
                context,
                this.settings.connectionName
            )
        );
```

The adapter is now working and is able to sign in the user using the magic code procedure, and it's able to retrieve the token using getUserToken afterwards. I haven't tested signOut yet.

I'll try to clean the code this weekend or at the start of next week, and either make a pull request (I'll have to investigate on how to do it properly though) or fork the repository and push it there.

**Comment by nestoralonsovina** [comment]
I was preparing the pull request, but I've found that some of the things required to make it work are only on version 4.6 of the botbuilder package, do you guys have any plans to update it?

Anyways, you can take a look at the changes here: [my fork](https://github.com/nestoralonsovina/botbuilder-community-js), if you are okay with updating the dependency will try to update the tests and create the pull request

**Comment by iMicknl** [comment]
Cool, @nestoralonsovina! Updating BotBuilder to 4.7.0 is not a problem, I am updating it in my PR (#142) also. 

If you create a PR, I will try to have a look soon. :-)
